#pragma once

#include <cstring>
#include <malloc.h>

#include <ogc/gx_struct.h>
#include <ogc/gx.h>
#include <ogc/system.h>
#include <ogc/video.h>

namespace video {

constexpr size_t FIFO_SIZE = (256 * 1024);

/// Data generated by `video::initialise()`. Used to initialise graphics.
struct initialisation_data {
    void* framebuffer;
    GXRModeObj* screen_mode;
    void* fifo_buffer;
};

/// Marks that the framebuffer is ready to copy.
void mark_ready_for_copy();
/// Initialises the video subsystem.
initialisation_data initialise(bool initialise_console);

} // namespace video
